spring:
  application:
    name: xbot

  datasource:
    url: jdbc:postgresql://localhost:5432/avocado
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  flyway:
    enabled: false

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true

api:
  x:
    url: 'https://api.twitter.com/2'
    consumer-key: 'your-consumer-key'
    consumer-secret: 'your-consumer-secret'
    access-token: 'your-access-token'
    access-token-secret: 'your-access-token-secret'
